=== zengineering/mcu-api/mcuapi/data/character_schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "PLACEHOLDER",
    "title": "Film",
    "description": "A character in the Marvel Cinematic Universe",
    "type": "object",
    "properties": {
        "name": {
            "type": "string",
            "description": "The name of the character"
        },
        "alter-ego": {
            "type": "string",
            "description": "The alternate/superhero name of the character"
        },
        "actors": {
            "type": "array",
            "description": "The actor(s) that have portrayed the character",
            "items": {
                "type": "string"
            }
        },
        "id": {
            "type": "integer",
            "description": "The unique identifier/index of the film"
        },
        "films" : {
            "type": "array",
            "description": "The id's of the films in which the character has appeared",
            "items": {
                "type": "integer"
            }
        }
    },
    "required": [
        "name",
        "alter-ego",
        "actors",
        "id",
        "films"
    ]
}

=== zengineering/mcu-api/mcuapi/data/characters.json
[
    {
        "name": "Tony Stark",
        "alter-ego": "Iron Man",
        "actors": [
            "Robert Downey Jr."
        ],
        "id": 1,
        "films" : [
            1, 3, 6, 7, 11, 13, 16, 19, 22
        ]
    },
    {
        "name": "James Rhodes",
        "alter-ego": "War Machine",
        "actors": [
            "Terrence Howard",
            "Don Cheadle"
        ],
        "id": 2,
        "films" : [
            1, 3, 7, 11, 13, 19, 22
        ]
    },
    {
        "name": "Pepper Potts",
        "alter-ego": "None",
        "actors": [
            "Gyneth Paltrow"
        ],
        "id": 3,
        "films" : [
            1, 3, 6, 7, 16, 19, 22
        ]
    },
    {
        "name": "Happy Hogan",
        "alter-ego": "None",
        "actors": [
            "Jon Favreau"
        ],
        "id": 4,
        "films" : [
            1, 3, 6, 7, 11, 16, 22
        ]
    },
    {
        "name": "Howard Stark",
        "alter-ego": "None",
        "actors": [
            "Dominic Cooper",
            "John Slattery"
        ],
        "id": 5,
        "films" : [
            3, 5, 12, 13, 22
        ]
    },
    {
        "name": "Jarvis",
        "alter-ego": "None",
        "actors": [
            "Paul Bettany"
        ],
        "id": 6,
        "films" : [
            1, 3, 6, 7, 11
        ]
    },
    {
        "name": "Steve Rogers",
        "alter-ego": "Captain America",
        "actors": [
            "Chris Evans"
        ],
        "id": 7,
        "films" : [
            5, 6, 9, 11, 13, 16, 19, 22
        ]
    },
    {
        "name": "James 'Bucky' Barnes",
        "alter-ego": "Winter Soldier",
        "actors": [
            "Sebastian Stan"
        ],
        "id": 8,
        "films": [
            5, 9, 13, 19, 22
        ]
    },
    {
        "name": "Peggy Carter",
        "alter-ego": "None",
        "actors": [
            "Hayley Atwell"
        ],
        "id": 9,
        "films": [
            5, 9, 11, 12, 22
        ]
    },
    {
        "name": "Sam Wilson",
        "alter-ego": "Falcon",
        "actors": [
            "Anthony Mackie"
        ],
        "id": 10,
        "films": [
            9, 11, 12, 13, 19, 22
        ]
    },
    {
        "name": "Johann Schmidt",
        "alter-ego": "Red Skull",
        "actors": [
            "Hugo Weaving",
            "Ross Marquand"
        ],
        "id": 11,
        "films" : [
            5, 19, 22
        ]
    },
    {
        "name": "Clint Barton",
        "alter-ego": "Hawkeye",
        "actors": [
            "Jeremy Renner"
        ],
        "id": 12,
        "films": [
            4, 6, 11, 13, 19, 22
        ]
    },
    {
        "name": "Natasha Romanoff",
        "alter-ego": "Black Widow",
        "actors": [
            "Scarlett Johansson"
        ],
        "id": 13,
        "films" : [
            3, 6, 9, 11, 13, 19, 22
        ]
    },
    {
        "name": "Nick Fury",
        "alter-ego": "None",
        "actors": [
            "Samuel Jackson"
        ],
        "id": 14,
        "films" : [
            3, 5, 6, 9, 11, 21, 22
        ]
    },
    {
        "name": "Phil Coulson",
        "alter-ego": "None",
        "actors": [
            "Clark Gregg"
        ],
        "id": 15,
        "films" : [
            1, 3, 4, 6, 21
        ]
    },
    {
        "name": "Maria Hill",
        "alter-ego": "None",
        "actors": [
            "Cobie Smulders"
        ],
        "id": 16,
        "films": [
            6, 9, 11, 22
        ]
    },
    {
        "name": "Everett Ross",
        "alter-ego": "None",
        "actors": [
            "Martin Freeman"
        ],
        "id": 17,
        "films": [
            13, 18
        ]
    },
    {
        "name": "Thor",
        "alter-ego": "None",
        "actors": [
            "Chris Hemsworth"
        ],
        "id": 18,
        "films": [
            4, 6, 8, 11, 17, 19, 22
        ]
    },
    {
        "name": "Jane Foster",
        "alter-ego": "None",
        "actors": [
            "Natalie Portman"
        ],
        "id": 19,
        "films" : [
            4, 8, 22
        ]
    },
    {
        "name": "Loki",
        "alter-ego": "None",
        "actors": [
            "Tom Hiddleston"
        ],
        "id": 20,
        "films" : [
            3, 6, 8, 17, 19, 22
        ]
    },
    {
        "name": "Heimdall",
        "alter-ego": "None",
        "actors": [
            "Idris Elba"
        ],
        "id": 21,
        "films" : [
            3, 8, 11, 17, 19, 22
        ]
    },
    {
        "name": "Odin",
        "alter-ego": "None",
        "actors": [
            "Anthony Hopkins"
        ],
        "id": 22,
        "films" : [
            3, 8, 17
        ]
    },
    {
        "name": "Frigga",
        "alter-ego": "None",
        "actors": [
            "Rene Russo"
        ],
        "id": 23,
        "films" : [
            3, 8, 22
        ]
    },
    {
        "name": "Sif",
        "alter-ego": "None",
        "actors": [
            "Jaimie Alexander"
        ],
        "id": 24,
        "films" : [
            3, 8
        ]
    },
    {
        "name": "Erik Selvig",
        "alter-ego": "None",
        "actors": [
            "Stellan Skarsgard"
        ],
        "id": 25,
        "films" : [
            3, 6, 8, 11
        ]
    },
    {
        "name": "Korg",
        "alter-ego": "None",
        "actors": [
            "Taika Waititi"
        ],
        "id": 26,
        "films" : [
            17, 22
        ]
    },
    {
        "name": "Peter Parker",
        "alter-ego": "Spider-Man",
        "actors": [
            "Tom Holland"
        ],
        "id": 27,
        "films" : [
            13, 16, 19, 22
        ]
    },
    {
        "name": "May Parker",
        "alter-ego": "Aunt May",
        "actors": [
            "Marisa Tomei"
        ],
        "id": 28,
        "films" : [
            13, 16, 22
        ]
    },
    {
        "name": "Ned Leeds",
        "alter-ego": "None",
        "actors": [
            "Jacob Batalon"
        ],
        "id": 29,
        "films" : [
            13, 16, 22
        ]
    },
    {
        "name": "Bruce Banner",
        "alter-ego": "Hulk",
        "actors": [
            "Edward Norton",
            "Mark Ruffalo"
        ],
        "id": 30,
        "films" : [
            2, 6, 11, 19, 22
        ]
    },
    {
        "name": "Thaddeus Ross",
        "alter-ego": "None",
        "actors": [
            "William Hurt"
        ],
        "id": 31,
        "films" : [
            2, 13, 19, 22
        ]
    },
    {
        "name": "Carol Danvers",
        "alter-ego": "Captain Marvel",
        "actors": [
            "Brie Larson"
        ],
        "id": 32,
        "films" : [
            21, 22
        ]
    },
    {
        "name": "Vision",
        "alter-ego": "None",
        "actors": [
            "Paul Bettany"
        ],
        "id": 33,
        "films" : [
            11, 13, 19, 22
        ]
    },
    {
        "name": "Wanda Maximoff",
        "alter-ego": "Scarlet Witch",
        "actors": [
            "Elizabeth Olsen"
        ],
        "id": 34,
        "films": [
            11, 13, 19, 22
        ]
    },
    {
        "name": "Peter Quill",
        "alter-ego": "Star-Lord",
        "actors": [
            "Chris Pratt"
        ],
        "id": 35,
        "films" : [
            10, 15, 19, 22
        ]
    },
    {
        "name": "Gamora",
        "alter-ego": "None",
        "actors": [
            "Zoe Saldana"
        ],
        "id": 36,
        "films" : [
            10, 15, 19, 22
        ]
    },
    {
        "name": "Drax",
        "alter-ego": "The Destroyer",
        "actors": [
            "Dave Bautista"
        ],
        "id": 37,
        "films" : [
            10, 15, 19, 22
        ]
    },
    {
        "name": "Rocket",
        "alter-ego": "None",
        "actors": [
            "Bradley Cooper"
        ],
        "id": 38,
        "films" : [
            10, 15, 19, 22
        ]

    },
    {
        "name": "Groot",
        "alter-ego": "None",
        "actors": [
            "Vin Diesel"
        ],
        "id": 39,
        "films" : [
            10, 15, 19, 22
        ]

    },
    {
        "name": "Nebula",
        "alter-ego": "None",
        "actors": [
            "Karen Gillan"
        ],
        "id": 40,
        "films" : [
            10, 15, 19, 22
        ]

    },
    {
        "name": "Mantis",
        "alter-ego": "None",
        "actors": [
            "Pom Klementieff"
        ],
        "id": 41,
        "films" : [
            15, 19, 22
        ]

    },
    {
        "name": "Ronan",
        "alter-ego": "The Accuser",
        "actors": [
            "Lee Pace"
        ],
        "id": 42,
        "films" : [
            10, 21
        ]
    },
    {
        "name": "Scott Lang",
        "alter-ego": "Ant-Man",
        "actors": [
            "Paul Rudd"
        ],
        "id": 43,
        "films" : [
            12, 13, 20, 22
        ]
    },
    {
        "name": "Hank Pym",
        "alter-ego": "Ant-Man",
        "actors": [
            "Michael Douglas"
        ],
        "id": 44,
        "films" : [
            12, 13, 20, 22
        ]
    },
    {
        "name": "Hope Van Dyne",
        "alter-ego": "Wasp",
        "actors": [
            "Evangeline Lily"
        ],
        "id": 45,
        "films" : [
            12, 13, 20, 22
        ]
    },
    {
        "name": "Stephen Strange",
        "alter-ego": "Doctor Strange",
        "actors": [
            "Benedict Cumberbatch"
        ],
        "id": 46,
        "films" : [
            14, 17, 19, 22
        ]
    },
    {
        "name": "Wong",
        "alter-ego": "None",
        "actors": [
            "Benedict Wong"
        ],
        "id": 47,
        "films" : [
            14, 19, 22
        ]
    },
    {
        "name": "The Ancient One",
        "alter-ego": "None",
        "actors": [
